### ISSUE TITLE
Repositories aren't synced with generics anymore

### ISSUE THREAD

**Issue by itrich** [SovereignCloudStack/generics#42]
After renaming all old `master` branches to `main`, all workflows that try to sync with this `generics` repository fail.

I've switched to `version: main` on all repositories, but the problem seems to be some kind of authorization problem.

```
> Pushing to SovereignCloudStack/gx-scs-identity-provider@chore/sync-with-generics-repository...
  git push origin chore/sync-with-generics-repository:refs/heads/chore/sync-with-generics-repository
    >> To https://github.com/SovereignCloudStack/gx-scs-identity-provider.git
    >>  ! [remote rejected] chore/sync-with-generics-repository -> chore/sync-with-generics-repository (refusing to allow a GitHub App to create or update workflow `.github/workflows/ci-test-workflow.yml` without `workflows` permission)
    >> error: failed to push some refs to 'https://github.com/SovereignCloudStack/gx-scs-identity-provider.git'
  
  Error: command [git push origin chore/sync-with-generics-repository:refs/heads/chore/sync-with-generics-repository] exited with code 1. message: To https://github.com/SovereignCloudStack/gx-scs-identity-provider.git
   ! [remote rejected] chore/sync-with-generics-repository -> chore/sync-with-generics-repository (refusing to allow a GitHub App to create or update workflow `.github/workflows/ci-test-workflow.yml` without `workflows` permission)
  error: failed to push some refs to 'https://github.com/SovereignCloudStack/gx-scs-identity-provider.git'
  
      at Command.value [as execAsync] (/home/runner/work/_actions/technote-space/create-pr-action/v2/lib/main.js:100210:31)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async GitHelper.value [as runCommand] (/home/runner/work/_actions/technote-space/create-pr-action/v2/lib/main.js:100291:45)
      at async GitHelper.value [as push] (/home/runner/work/_actions/technote-space/create-pr-action/v2/lib/main.js:100725:17)
      at async push (/home/runner/work/_actions/technote-space/create-pr-action/v2/lib/main.js:107342:5)
      at async diffProcess (/home/runner/work/_actions/technote-space/create-pr-action/v2/lib/main.js:107854:5)
      at async createPr (/home/runner/work/_actions/technote-space/create-pr-action/v2/lib/main.js:107890:31)
      at async runCreatePr (/home/runner/work/_actions/technote-space/create-pr-action/v2/lib/main.js:107949:28)
      at async execute (/home/runner/work/_actions/technote-space/create-pr-action/v2/lib/main.js:107995:9)
      at async main (/home/runner/work/_actions/technote-space/create-pr-action/v2/lib/main.js:108018:5)  
```

Let's get this up and running again.

In particular, these repositories are:
- [ ] gx-scs-identity-provider
- [x] k8s-cassandra
- [x] k8s-cortex
- [x] k8s-gatekeeper
- [x] k8s-grafana
- [ ] k8s-harbor
- [x] k8s-minio
- [x] k8s-prometheus
- [ ] k8s-template

**Comment by joshmue** [comment]
I'll take a look into the k8s-harbor repo.

For the other ones, I think it's fair to archive a bunch of these repositories and only revive if they are actually used.

IMHO that would include k8s-cassandra, k8s-cortex, k8s-gatekeeper, k8s-grafana, k8s-minio, and k8s-prometheus.

**Comment by itrich** [comment]
See https://github.com/SovereignCloudStack/k8s-template/issues/1

**Comment by garloff** [comment]
Kurt to clean up and then add push permissions to the repo. @joshmue to advise.

**Comment by jschoone** [comment]
Looks like this is done @garloff @joshmue ?
